DNA1 = "CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCCTCCCACTAATAATTCTGAGG"
DNA2 = "CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCTATATCCATTTGTCAGCAGACACGC"
DNA3 = "CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGACTGGGAACCTGCGGGCAGTAGGTGGAAT"
DNA4 = "CCCCCCCCCCCCGF" #12 C, 1G, 1F

def biggestfinder():
    pass


def DNAcount(DNA):
    C = DNA.count("C")
    G = DNA.count("G")
    GC = C + G
    Percentage = GC/len(DNA)
    print(Percentage)
    print(GC)
    print(len(DNA))



DNAcount(DNA4)

