dna_1 = "ATGAATCGCACCGCGGGTCCCGCTCTGTCGTACACTAGACTCTTAGTTAAGGGTACGCTTACCAAGCTGTGTTGATCTATCAGGGTTCGTGGACTTAGCTATATACCTGGATGCTCAGGACTCGCACGAGAACGAAAATTCCGCGTCACCACGAAAGTTCCGATATTGCTGTCACAAAAACGCAGTATTCATGGATCCTGATGTGTGCTTAAACACGGGCCTATATTCATACGATAGTCTTATGGCACTATTTGCGCGCACTGTATGACAGCAAAAAAGCTTGGAGCTAGGCGAAGTCCGAGACGTATTACAAACCACCCAATTCTAGGATCAATCACCATTCCTACGTAACACGCGTTCTCAGATTGTATGCGGTTTAATAGTACCTCGGGCGGATCCCCCAAATAATGCTCGATCCGTCTAGTCGTGTGTTCGACAGCGACCTAGGGAGGTGGCCGCAAGCATAGAGAAGCCGCGATCACGTTATCTGATGATGATGACAAAGCACTAATCCAGTATCTAGTCAGAAATAATGCAAAGCGACACTAGTACTAGTCCTCCCGTCCACGCCCACCGAGCTGTGCAAATTTCTTGTCTTCGATAGGGAACGATAACACGGCTGCCCACGTATCTCTGTCCGGTGGACACAGCAAGAGGGTTGAATGCAGATACGCTGTACAGTATGGATGTGTGTAATCTAAAGAAGCGGCGTAACTTTACCGCCATTCCCCGTTATCGAAGTTTTTAATCGGAGGACGCCAAATACACACACGCCGATCGTTCAGTGGGACCTGATAGGATGGTTATTTTCTTTGCGCACCGATCCTTATATCGAGAAACGTATACCTCTGGGATTAAGAGTAACATAGCCGATTCGATCCTTCCACGCATCGAGAGCCAAAAATTATAAGTCCACCGCTAAGTGTCCACGTCAACACGCGCAGGCGTTCGTAAACAGGCTTCACGAGGTGGCCTAATTGATACGC"
A_count = 0
T_count = 0
C_count = 0
G_count = 0

length = len(dna_1)
print(length)

for i in range(length):
    if dna_1[i] == "A":
        A_count += 1
    elif dna_1[i] == "T":
        T_count += 1
    elif dna_1[i] == "C":
        C_count += 1
    elif dna_1[i] == "G":
        G_count += 1

print(A_count)
print(T_count)
print(C_count)
print(G_count)


nmb_perm_list = nmb_perm[::1]
for i in list(nmb_perm_list):
    i.replace(" ", " \n")

print(nmb_perm_list)
#print(len(nmb_perm))
print()